export { default as Root } from "./root";
export { default as ProjectList } from "./project/projectList";
export { default as ProjectDetail } from "./project/projectDetail";
export { default as ProjectCreate } from "./project/createProject";
export { default as ProjectUpdate } from "./project/updateProject";
export { default as Register } from "./auth/Register";
export { default as Profile } from "./Profile";
export { default as Login } from "./auth/Login";
export { default as PeopleList } from "./PeopleList";
