export { default as Root } from "./rootTs";
// export { default as ProjectList } from "./project/projectList";
export { default as ProjectList } from "./project/projectListTs";
export { default as ProjectDetail } from "./project/projectDetail";
export { default as ProjectCreate } from "./project/createProjectTs";
export { default as ProjectUpdate } from "./project/updateProject";
export { default as Register } from "./auth/Register";
export { default as RegisterPage } from "./auth/RegisterTs";
export { default as Profile } from "./Profile";
export { default as Login } from "./auth/Login";
export { default as LoginPage } from "./auth/LoginTs";
export { default as PeopleList } from "./PeopleList";
